### ISSUE TITLE
dlock13.* services restarting

### ISSUE THREAD

**Issue by tingox** [bitraf/dlock13#6]
(retroactively documenting a problem that was "fixed" earlier this afternoon)
This afternoon (at around 15:30 local time) the front door and the doors at the second floor (ok, first floor for English people) stopped working, even if the web page still said "door open" when you pressed the button. Also the guest button didn't light up.
Everything seemed to be in order, expect for one thing, the dlock13.* services on boxy2 was restarting the whole time. From the journalctl log:
`Nov 05 15:48:19 boxy2 systemd[1]: Stopping dlock13@frontdoor.service...`
`Nov 05 15:48:19 boxy2 systemd[1]: Starting dlock13@frontdoor.service...`
`Nov 05 15:48:19 boxy2 sh[9107]: mqtt: Connecting to mqtt.bitraf.no:1883, client_id=, keep_alive=180`
`Nov 05 15:48:19 boxy2 sh[9107]: mqtt: mosquitto_connect`
`Nov 05 15:48:19 boxy2 sh[9107]: mqtt: yes`
`Nov 05 15:48:19 boxy2 sh[9107]: mqtt: mosquitto_disconnect: The client is not currently connected.`
`Nov 05 15:48:19 boxy2 sh[9107]: terminate called after throwing an instance of 'trygvis::mqtt_support::mqtt_error'`
`Nov 05 15:48:19 boxy2 sh[9107]: what():  mosquitto_connect: Unknown error.`
`Nov 05 15:48:19 boxy2 systemd[1]: dlock13@2floor.service: main process exited, code=exited, status=134/n/a`
`Nov 05 15:48:19 boxy2 systemd[1]: Unit dlock13@2floor.service entered failed state.`
`Nov 05 15:48:19 boxy2 sh[9107]: Aborted`
nothing else seemed wrong. With no other indications, I eventually restarted boxy2 ('shutdown -r now') and that seems to have fixed the problem - for now.

**Comment by tingox** [comment]
a guess at the cause is that the Pi (boxy2) ran out of memory.

**Comment by tingox** [comment]
A restart of boxy2 `shutdown -r now` fixed the problem, so close this.

**Comment by jenschr** [comment]
The empty ClientID looks odd? I never tried, but could make sense if that caused a reconnect

**Comment by tingox** [comment]
I think that the program (or SystemD) just "censors" sensitive fields in the log. Here is a bit of the log when it is working:
`Nov 05 16:23:19 boxy2 systemd[1]: Started dlock13@frontdoor.service.`
`Nov 05 16:23:19 boxy2 sh[662]: Role:   frontdoor`
`Nov 05 16:23:19 boxy2 sh[662]: File:   /sys/class/gpio/gpio10/value`
`Nov 05 16:23:19 boxy2 sh[662]: Prefix: /bitraf/door/`
`Nov 05 16:23:19 boxy2 sh[662]: host: mqtt.bitraf.no`
`Nov 05 16:23:19 boxy2 sh[662]: client_id:`
`Nov 05 16:23:19 boxy2 sh[662]: keep_alive: 180`
`Nov 05 16:23:19 boxy2 sh[662]: clean_session: 1`
`Nov 05 16:23:19 boxy2 sh[662]: mqtt: Connecting to mqtt.bitraf.no:1883, client_id=, keep_alive=180`
`Nov 05 16:23:19 boxy2 sh[662]: mqtt: mosquitto_connect`
`Nov 05 16:23:19 boxy2 sh[662]: DoorLock set GPIO: /sys/class/gpio/gpio10/value to 0`
`Nov 05 16:23:19 boxy2 sh[662]: mqtt: Publishing 5 bytes to /bitraf/door/frontdoor/isopen`
`Nov 05 16:23:19 boxy2 sh[662]: mqtt: message ACKed, message id=1`
no client_id there either
